### ISSUE TITLE
Draft tutorial for the automated a11y test tool

### ISSUE THREAD

**Issue by cplkake** [CivicTechTO/polis#14]
- [x] Test [Axe accessibility tool](https://www.deque.com/axe/) for easy of use
    - [ ] Is it easy to use?
    - [ ] Can the output converted to output template format easily?
- [x] #17
    - [ ] Is it easy to use?
    - [ ] Can the output converted to output template format easily?
- [x] A set of instructions that anyone can follow and get a test result from the automated test tool in Wiki [auto tool tutorial section](https://github.com/CivicTechTO/polis/wiki/Accessibility-Test-Guideline#auto-tool-tutorial)
    - The title (auto tool tutorial) is editable

**Comment by cplkake** [comment]
Progress update: neither axe not WAVE has a way to output results directly. Doing so with axe would require a paid subscription whereas with the WAVE browser extension, there is no output feature at all. For now, getting output of tests would require manually filling in template. I am in the process of writing out a tutorial for the two extensions. Rachel is looking into potentially using Lighthouse and having a JSON output be converted to a CSV format progammatically and uploaded to the template.

**Comment by NewJerseyStyle** [comment]
Reading our meeting notes, I found `WebAIM`, is it another option beside of `Axe`, `WAVE`, `Lighthouse`?

**Comment by cplkake** [comment]
> Reading our meeting notes, I found `WebAIM`, is it another option beside of `Axe`, `WAVE`, `Lighthouse`?

WebAIM is the non-profit organization that helped create the WAVE tool

**Comment by cplkake** [comment]
I have written a tutorial for running the test [here](https://github.com/CivicTechTO/polis/wiki/Accessibility-Test-Guideline#automated-accessibility-tool-tutorial)
