### ISSUE TITLE
Accessibility issue in Accessibility Test Guideline

### ISSUE THREAD

**Issue by NewJerseyStyle** [CivicTechTO/polis#19]
Accessibility issue in [Test with Automated Accessibility Tool](https://github.com/CivicTechTO/polis/wiki/Accessibility-Test-Guideline#test-with-automated-accessibility-tool) of Accessibility Test Guideline
* Some of the short cuts in using the tools are not compatible cross platform, need to replace
* The button in using the devtool is not easy to find, would be better to add image
* A couple steps from the flow are not mentioned.

**Comment by Nini-indesign** [comment]
Could you assign me to the issue?

**Comment by Nini-indesign** [comment]
The necessary edits to the document have been made. Closing the issue.
