### ISSUE TITLE
Network issue after first build with docker compose

### ISSUE THREAD

**Issue by NewJerseyStyle** [CivicTechTO/polis#8]
**Expected behavior**:
showing polis index page after starting docker compose instances

**Actual behavior**:
come across a timeout error in browser to web server after building and running the polis service

**To Reproduce**:
`cp example.env .env`  
`docker compose up --build`  
*error occur  

**Device information**:
MacBook

**Additional context**:
This can be resolved by restarting all instances:  
`docker compose down`  
`docker compose up`  
*usually error disappear

But it would be better if it can be resolved

**Comment by Zen-cronic** [comment]
similar error here on the first build. But restarting does the trick just like you mentioned.

**Comment by NewJerseyStyle** [comment]
On some Windows 11 with Docker desktop and Ubuntu server 22.04 with Docker CE environment this error does not occur. Interesting...

**Comment by Zen-cronic** [comment]
oh i see, mine's Ubuntu 24.04, that's probably why.

**Comment by NewJerseyStyle** [comment]
I assume it can also be solved by skipping local building of image #101

**Comment by NewJerseyStyle** [comment]
Did not hit any problem after #101
